name: api
on:
  push:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: make api-install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
